name: Build and push a kafka docker image for our hermetic tests

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'SHA or branch to deploy'
        required: true
        type: string
        default: 'main'
env:
  IMAGE_NAME_CLI: ghcr.io/resourcely-inc/kafka:for_hermetic_tests

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME_CLI .
        docker images # for debugging purposes

    - name: Login to Github Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push kafka Docker Image to Github Container Registry
      run: docker push $IMAGE_NAME_CLI
